version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php
        container_name: info-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: info-app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - ip-app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: ipserver
        restart: unless-stopped
        tty: true
        ports:
            - "85:85"
            - "445:445"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - ip-app-network

    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: ip-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: IP_DB
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - ip-app-network

#Docker Networks
networks:
    ip-app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
